### PR TITLE
issue no :#50 

### PR DESCRIPTION
**Pull request by PRITISH212121**
added better ui effects,
hover effect on buttons, 
added gradient color,
 removed the logo background so that it merges properly,
applied on all pages
swoc3

### CODE REVIEW

**Comment by PRITISH212121** [comment]
@sagnik3788 check this out,done with all the pages

**Comment by sagnik3788** [comment]
@PRITISH212121 great

**Comment by PRITISH212121** [comment]
is it good enough to merge? @sagnik3788

**Comment by sagnik3788** [comment]
@PRITISH212121 resolve the conflicts

**Pull request closed without merging**
