### PR TITLE
Update Of Serach Help Cart Item Icon

### PR DESCRIPTION
**Pull request by kavya020805**

### CODE REVIEW

**Comment by sagnik3788** [comment]
@kavya020805 please share a shreenshot of the updated part

**Comment by kavya020805** [comment]
image

**Comment by sagnik3788** [comment]
looks good @kavya020805

**Comment by sagnik3788** [comment]
give @kavya020805 25 points

**Comment by sagnik3788** [comment]
give @kavya020805 25 points

**Comment by kavya020805** [comment]
give @kavya020805 25 points

**Pull request merged**
