### PR TITLE
Footer UI

### PR DESCRIPTION
**Pull request by sambitsingha**
## Description: 
The PR updates the existing footer UI to a new one , which seems more organic to the theme of the website. A new background image , new icons and and logo was used to change the look of the footer.
## Screenshots: 
Screenshot (146)

### CODE REVIEW

**Comment by sambitsingha** [comment]
@sagnik3788 Please review the PR

**Comment by sagnik3788** [comment]
@sambitsingha actually the background image not matches with the whole page can you make it more simpler

**Comment by sambitsingha** [comment]
Alright .. working on it. :)

**Comment by sambitsingha** [comment]
@sagnik3788 Footer background changed , responsivesness of the footer and **Merge conflicts** resolved

**Comment by sagnik3788** [comment]
@sambitsingha check preview

**Comment by sambitsingha** [comment]
The entire CSS is not loading. :(

**Comment by sambitsingha** [comment]
@sagnik3788 Check pls

**Comment by sagnik3788** [comment]
@sambitsingha is it working now ?

**Comment by sambitsingha** [comment]
> @sambitsingha is it working now ?

The thing is working perfectly in my machine, But the entire CSS is gone in the preview

**Comment by sagnik3788** [comment]
@sambitsingha all code are updated in your local machine?

**Comment by sambitsingha** [comment]
> @sambitsingha all code are updated in your local machine?

wait , checking ..

**Comment by sambitsingha** [comment]
@sagnik3788 The problem is with the html file. I need to redo this before any other PR is merged ig.

**Comment by sambitsingha** [comment]
@sagnik3788 I am closing this PR. Will check what's wrong and open a new PR

**Pull request closed without merging**
