### PR TITLE
Improved README.md File

### PR DESCRIPTION
**Pull request by abhinab-choudhury**
# Ref : #9

### CODE REVIEW

**Comment by sagnik3788** [comment]
@abhinab-choudhury share screenshot of the updated part

**Comment by abhinab-choudhury** [comment]
img

**Comment by abhinab-choudhury** [comment]
1_img

**Comment by sagnik3788** [comment]
@abhinab-choudhury add your profile as well

**Comment by abhinab-choudhury** [comment]
It will get added automatically after merging the PR

**Comment by sagnik3788** [comment]
great @abhinab-choudhury

**Pull request merged**
