### PR TITLE
issue no : #50 enhanced navbar ui

### PR DESCRIPTION
**Pull request by PRITISH212121**
added better navbar effects,
applied on each page,
resolved conflicts
swoc3

### CODE REVIEW

**Comment by PRITISH212121** [comment]
@sagnik3788  is it ok now?

**Comment by sagnik3788** [comment]
@PRITISH212121 there are some issue with the navbar 
Screenshot from 2024-01-05 22-51-38

**Comment by PRITISH212121** [comment]
@sagnik3788 give me some time, must have been due to pull request,resolving asap

**Comment by PRITISH212121** [comment]
@sagnik3788  resolved every error after pull request,now is it okay?

**Comment by sagnik3788** [comment]
logo not showing @PRITISH212121

**Pull request closed without merging**
