### PR TITLE
Enhanced typography

### PR DESCRIPTION
**Pull request by muskan42**
changed font family, font size, alignment of buttons and the presentation of texts on banners.

### CODE REVIEW

**Comment by muskan42** [comment]
Screenshot (60)
Screenshot (62)
Screenshot (61)

**Comment by muskan42** [comment]
Screenshot (62)
Screenshot (61)
Screenshot (60)

**Comment by sagnik3788** [comment]
apart from this font looks good

**Comment by muskan42** [comment]
I have resolved conflicts and added some changes as well.

**Comment by muskan42** [comment]
Screenshot 2024-01-07 024345

**Comment by sagnik3788** [comment]
#51

**Pull request merged**
