### PR TITLE
New Logo

### PR DESCRIPTION
**Pull request by kavya020805**

### CODE REVIEW

**Comment by sagnik3788** [comment]
@kavya020805  share  screenshot  of the updated part

**Comment by kavya020805** [comment]
image
@sagnik3788

**Comment by sagnik3788** [comment]
@kavya020805  shift the logo to the corner

**Comment by kavya020805** [comment]
image
@sagnik3788

**Comment by kavya020805** [comment]
image
@sagnik3788

**Comment by sagnik3788** [comment]
give @kavya020805 25 points

**Comment by kavya020805** [comment]
@sagnik3788 the PR was old one, where the logo was not centered...
In next PR of other issue i will keep the logo on left side

**Comment by sagnik3788** [comment]
@kavya020805 np create another pr of the updated section 🙂👍

**Pull request merged**
