### PR TITLE
Updating Home Page

### PR DESCRIPTION
**Pull request by sidharth2829**
Made the following the changes.
1) Realigned the nav-bar icons.
2) Added vertical borders between footer-tags, top-margin to footer, and text-shadow to footer-tags heading. 
3) Added a hover effect to word "Sagnik" in footer-end.

### CODE REVIEW

**Comment by sagnik3788** [comment]
1.remove the borders 
2.shadow effect not looks good 
3.fix the gap of this 
Screenshot from 2023-12-28 23-56-06
4.also this gap as well

**Comment by sagnik3788** [comment]
@sidharth2829 just add these features

**Comment by sidharth2829** [comment]
Both these gaps are not visible on my device, can i know ur device aspect ratio?

**Comment by sagnik3788** [comment]
It's 16:9 btw if  that's the case then just  remove 1 and 2 so that I can merge it

**Comment by sidharth2829** [comment]
Ok, but i have a small request. I have participated in SWOC and contributions will count from 1 Jan. So can u merge my PR then.

**Comment by sagnik3788** [comment]
@sidharth2829 sure please mention from next time when you work on any issue about swoc or any other program

**Comment by sidharth2829** [comment]
Thanks a lot @sagnik3788 , i have commit the final changes. You can check them.

**Pull request merged**
