### PR TITLE
Improved help for customers 

### PR DESCRIPTION
**Pull request by ayan-joshi**
Now all are aligned properly also added underline to the options or the quiestions of the help for customers , 
basically solved the problem in the issue #4 
have a look @sagnik3788

### CODE REVIEW

**Comment by sagnik3788** [comment]
please share a shreenshot of the updated part @ayan-joshi

**Comment by ayan-joshi** [comment]
Screenshot 2023-10-18 010714

Worked as mentioned in the issue @sagnik3788

**Comment by sagnik3788** [comment]
give @ayan-joshi  75 points

**Comment by sagnik3788** [comment]
give @ayan-joshi 75 points

**Pull request merged**
