### PR TITLE
Making home page responsive

### PR DESCRIPTION
**Pull request by sidharth2829**

### CODE REVIEW

**Comment by sagnik3788** [comment]
@sidharth2829  can you share the updated part or issue related to this pr

**Comment by sidharth2829** [comment]
https://github.com/sagnik3788/FlavorFleet/assets/111569459/fb99b5f5-fd8e-44a4-9872-74160fadf68e


@sagnik3788 , i have made the Home Page responsive for all screens

**Comment by sagnik3788** [comment]
@sidharth2829 mention the issue number

**Comment by sidharth2829** [comment]
#38

**Pull request merged**
