### PR TITLE
Updated Searh Bar

### PR DESCRIPTION
**Pull request by abhinab-choudhury**
# Ref: #2

### CODE REVIEW

**Comment by sagnik3788** [comment]
share the updated part  @abhinab-choudhury

**Comment by abhinab-choudhury** [comment]
[Image](https://ibb.co/DVgcr3P)

**Comment by abhinab-choudhury** [comment]
Can you make this issue a part of Hacktoberfest2023

**Comment by abhinab-choudhury** [comment]
https://github.com/sagnik3788/FlavorFleet/assets/132006996/415091da-abc6-4b42-8a31-8b2a08393db8

**Comment by sagnik3788** [comment]
@abhinab-choudhury looks good thanks for  your contribution

**Pull request merged**
